### ISSUE TITLE
Held Item Evolutions don't stay

### ISSUE THREAD

**Issue by DanDragonWolf** [kingtrapinch/Twilight-Forms#1]
Noticed this while trying to evolve Grotle into Twilight Oak Torterra, the second the sapling is consumed, the evo gets removed from the list because you have to add `"permanent": true,` to each held item evolution that takes the item now

**Comment by DanDragonWolf** [comment]
Also want to say that I don't think you have to list moves and evolutions that are already in the main species file in the species additions, just what you're adding.

**Comment by justiniantheemperor** [comment]
Thanks for this tip! I'll make this change to Torterra in the next update. I've also been meaning to clean up the species additions to make it more compatible with other versions.

**Comment by kingtrapinch** [comment]
Fixed in v1.1.1
