### ISSUE TITLE
Issue with textures

### ISSUE THREAD

**Issue by Cub3x880** [kingtrapinch/Twilight-Forms#2]
im not sure whats wrong because i followed the instructions but the pokemon spawn but as regular pokemon,
![image_2024-05-28_173157659](https://github.com/kingtrapinch/Twilight-Forms/assets/171089163/7e2919fa-4371-4898-9bd0-34c63903e5b1)

**Comment by kingtrapinch** [comment]
Let me take a look into this. Thanks for letting me know!

**Comment by kingtrapinch** [comment]
@Cub3x880  Do you know if this is happening for any other spawns in the Twilight Forest? If none of the forms are loading, you probably just need to add the pack to your resource packs folder and make sure it's enabled.

**Comment by Cub3x880** [comment]
ill check if its enabled but im pretty sure i followed the steps perfectly

**Comment by Cub3x880** [comment]
ah ty for the help, i did not have it enabled. this is my first time doing this so i wasnt too sure how to

**Comment by kingtrapinch** [comment]
No worries! Always here to help :)
