### ISSUE TITLE
Twilight mons don't have textures

### ISSUE THREAD

**Issue by YoDavidBestT** [kingtrapinch/Twilight-Forms#3]
When I entered the Twilight Forest dimension and look for the new Twilight forms they were a substitute or just their normal variants. They had their new types and stuff but no textures
![Arbok](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/c7587a8e-17a3-42e4-8392-4ee3e9133033)
![Necromarrow](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/5d3351eb-052a-4b61-8582-149120c58fca)
![Marowak](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/8e04d384-fbee-41c5-b064-f705fb88b8d5)

**Comment by kingtrapinch** [comment]
You need to place the pack in the datapack and resource pack folder to work. You also need to make sure the resourcepack is enabled from the Minecraft settings menu.

**Comment by YoDavidBestT** [comment]
Thanks :D
![2024-06-27_19 51 41](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/4537d835-a113-4d88-a89b-d747ab03127f)
![2024-06-27_19 52 33](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/ba7fb2de-2f93-40b2-8ec0-dcbfc683b50f)
![2024-06-27_19 52 36](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/8e88d8ab-afc0-4a55-aab0-fb3582a886c1)

**Comment by YoDavidBestT** [comment]
Wow, Shadow Blastoise is so much bigger compared to normal Blastoise, it would be fun if the rest of the Shadow mons would me bigger than their counterparts
![2024-06-27_19 57 18](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/dec0cd1a-a57b-4c94-b316-fe46f1b4370a)
![2024-06-27_19 57 36](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/adef8f4e-93a2-4281-93a2-e2b7b9e95117)
![2024-06-27_19 57 52](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/1b9bd8da-2d01-4ceb-9f94-cb912810d50d)
![2024-06-27_20 00 14](https://github.com/kingtrapinch/Twilight-Forms/assets/114753609/90e32d29-9deb-46ef-a873-83310558fe3d)
